name: Run tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    # strategy:
    #   fail-fast: true
    #   matrix:
    #     nvim_version:
    #       - stable
    #       - nightly

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Setup Vim
    #   uses: rhysd/action-setup-vim@v1.2.8
    #   with:
    #     neovim: true
    #     version: ${{ matrix.nvim_version }}

    - name: Setup neovim
      run: |
        curl -OL https://raw.githubusercontent.com/norcalli/bot-ci/master/scripts/github-actions-setup.sh
        source github-actions-setup.sh nightly-x64

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U covimerage
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test
      run: |
        ./run_test.sh

    - name: Update coverage
      run: |
        covimerage xml
        bash <(curl -s https://codecov.io/bash) -f coverage.xml
